#ifndef CONFIG_H
#define CONFIG_H

#include <raylib/raylib.h>

#define WINDOW_TITLE "Sulla"
#define DEFAULT_SCREEN_WIDTH 1280
#define DEFAULT_SCREEN_HEIGHT 720
#define GRID_SIZE 32.0f

#define BASE_PART_WIDTH 40.0f
#define BASE_PART_HEIGHT 40.0f
#define PIN_SIZE 8.0f
#define PIN_COLLISION_RADIUS_MOD 1.5f
#define PIN_SPACING 20.0f
#define PIN_Y_OFFSET_BASE 10.0f
#define PART_LABEL_OFFSET 2.0f
#define PART_LED_SIZE 16.0f
#define DRAG_THRESHOLD 5.0f
#define MIN_PART_WIDTH 40.0f
#define SOURCE_TOGGLE_SIZE 12.0f
#define TEXT_PADDING 10.0f

#define WIRE_COLLISION_THRESHOLD 10.0f
#define WIRE_HITBOX_PADDING 4.0f
#define WIRE_HITBOX_SIZE 6.0f
#define WIRE_THICKNESS 2.0f
#define WIRE_ARROW_SIZE 6.0f

#define COLOR_BG_LIGHT RAYWHITE
#define COLOR_GRID_LIGHT Fade(LIGHTGRAY, 0.5f)
#define COLOR_PART_BG_LIGHT WHITE
#define COLOR_PART_BORDER_LIGHT BLACK
#define COLOR_TEXT_LIGHT BLACK
#define COLOR_UI_BG_LIGHT RAYWHITE
#define COLOR_UI_BORDER_LIGHT GRAY

#define COLOR_BG_DARK { 30, 30, 30, 255 }
#define COLOR_GRID_DARK { 60, 60, 60, 255 }
#define COLOR_PART_BG_DARK { 50, 50, 50, 255 }
#define COLOR_PART_BORDER_DARK LIGHTGRAY
#define COLOR_TEXT_DARK RAYWHITE
#define COLOR_UI_BG_DARK { 40, 40, 40, 255 }
#define COLOR_UI_BORDER_DARK { 80, 80, 80, 255 }

#define COLOR_WIRE_OFF BLACK
#define COLOR_WIRE_OFF_DARK LIGHTGRAY
#define COLOR_WIRE_ON DARKGREEN
#define COLOR_WIRE_ON_DARK GREEN
#define COLOR_WIRE_SELECTED ORANGE
#define COLOR_PART_SELECTED ORANGE
#define COLOR_LED_ON GREEN
#define COLOR_LED_OFF DARKGREEN
#define COLOR_LED_OUT_ON RED
#define COLOR_LED_OUT_OFF DARKGRAY
#define COLOR_SELECTION_BOX Fade(BLUE, 0.3f)
#define COLOR_SELECTION_BORDER BLUE

#define TOOLBAR_HEIGHT 40.0f
#define TOOLBAR_BTN_WIDTH 60.0f
#define TOOLBAR_BTN_HEIGHT 30.0f
#define TOOLBAR_BTN_SPACING 10.0f
#define TOOLBAR_PADDING 5.0f

#define DEFAULT_SIDEMENU_WIDTH 200.0f
#define SIDEMENU_PADDING_X 10.0f
#define SIDEMENU_Y_START 50.0f
#define SIDEMENU_HEADER_TEXT_SIZE 20
#define SIDEMENU_HEADER_MARGIN 30.0f
#define SIDEMENU_BUTTON_HEIGHT 30.0f
#define SIDEMENU_BUTTON_MARGIN 10.0f
#define SIDEMENU_BUTTON_SPACING 40.0f
#define SIDEMENU_BUTTON_TEXT_OFFSET_X 20.0f
#define SIDEMENU_BUTTON_TEXT_OFFSET_Y 5.0f
#define SIDEMENU_BUTTON_TEXT_SIZE 20
#define SIDEMENU_LIST_SPACING 35.0f
#define SIDEMENU_LIST_TEXT_SIZE 10
#define SIDEMENU_LIST_TEXT_OFFSET_X 15.0f
#define SIDEMENU_LIST_TEXT_OFFSET_Y 8.0f
#define SIDEMENU_DELETE_BTN_SIZE 20.0f

#define CM_WIDTH 120.0f
#define CM_ROW_HEIGHT 25.0f
#define CM_TEXT_OFFSET_X 5.0f
#define CM_TEXT_OFFSET_Y 5.0f
#define CM_TEXT_SIZE 10

#define DIALOG_WIDTH 320.0f
#define DIALOG_HEIGHT 120.0f
#define DIALOG_INPUT_Y 50.0f
#define DIALOG_INPUT_HEIGHT 30.0f
#define SAVE_FILENAME_MAX_LEN 63

#define SAVE_DIALOG_WIDTH 300.0f
#define SAVE_DIALOG_HEIGHT 100.0f
#define SAVE_DIALOG_TEXT_Y_OFFSET 40.0f
#define SAVE_DIALOG_TEXT_X_OFFSET 140.0f
#define SAVE_DIALOG_INPUT_Y_OFFSET 10.0f
#define SAVE_DIALOG_INPUT_HEIGHT 30.0f
#define SAVE_DIALOG_INPUT_WIDTH 280.0f
#define SAVE_DIALOG_EXT_OFFSET 285.0f

#define SAVE_DIALOG_BTN_WIDTH 80.0f
#define SAVE_DIALOG_BTN_HEIGHT 25.0f
#define SAVE_DIALOG_BTN_Y_OFFSET 80.0f
#define SAVE_DIALOG_BTN_SPACING 20.0f

#define HELP_MENU_WIDTH 320.0f
#define HELP_MENU_HEIGHT 450.0f
#define HELP_PADDING 10.0f
#define HELP_SHADOW_OFFSET 5.0f
#define HELP_HEADER_SIZE 20
#define HELP_TEXT_SIZE 10
#define HELP_LINE_SPACING 15.0f
#define HELP_SECTION_SPACING 25.0f

#define HUD_X_OFFSET 150.0f
#define HUD_Y 50.0f
#define HUD_FONT_SIZE 20
#define HUD_BTN_SIZE 20.0f

#define ZOOM_MIN 0.1f
#define ZOOM_MAX 5.0f
#define ZOOM_SPEED 0.1f

#define INPUT_REPEAT_DELAY 0.5f
#define INPUT_REPEAT_RATE 0.05f

#endif
