#ifndef CONFIG_H
#define CONFIG_H

#include <raylib/raylib.h>

// Window & Grid
#define WINDOW_TITLE "Sulla Logic Sim"
#define DEFAULT_SCREEN_WIDTH 1280
#define DEFAULT_SCREEN_HEIGHT 720
#define GRID_SIZE 32.0f

// Parts & Pins
#define PART_SIZE 40.0f
#define PIN_SIZE 8.0f
#define PIN_COLLISION_RADIUS_MOD 1.5f
#define PIN_Y_OFFSET_BASE 5.0f
#define PIN_SPACING 20.0f
#define PART_LABEL_OFFSET 2.0f
#define PART_LED_OFFSET_X 10.0f
#define PART_LED_OFFSET_Y 15.0f
#define PART_LED_SIZE 20.0f
#define DRAG_THRESHOLD 5.0f

// Wire Interaction
#define WIRE_COLLISION_THRESHOLD 10.0f
#define WIRE_HITBOX_PADDING 2.0f
#define WIRE_HITBOX_SIZE 4.0f
#define WIRE_THICKNESS 2.0f

// Colors
#define COLOR_WIRE_OFF BLACK
#define COLOR_WIRE_ON DARKGREEN
#define COLOR_WIRE_SELECTED ORANGE
#define COLOR_PART_BG WHITE
#define COLOR_PART_BORDER BLACK
#define COLOR_PART_SELECTED ORANGE
#define COLOR_LED_ON GREEN
#define COLOR_LED_OFF DARKGREEN
#define COLOR_LED_OUT_ON RED
#define COLOR_LED_OUT_OFF DARKGRAY

// Side Menu
#define DEFAULT_SIDEMENU_WIDTH 200.0f
#define SIDEMENU_PADDING_X 10.0f
#define SIDEMENU_Y_START 10.0f
#define SIDEMENU_HEADER_TEXT_SIZE 20
#define SIDEMENU_HEADER_MARGIN 30.0f
#define SIDEMENU_BUTTON_HEIGHT 30.0f
#define SIDEMENU_BUTTON_MARGIN 10.0f
#define SIDEMENU_BUTTON_SPACING 40.0f
#define SIDEMENU_BUTTON_TEXT_OFFSET_X 20.0f
#define SIDEMENU_BUTTON_TEXT_OFFSET_Y 5.0f
#define SIDEMENU_BUTTON_TEXT_SIZE 20
#define SIDEMENU_LIST_SPACING 35.0f
#define SIDEMENU_LIST_TEXT_SIZE 10
#define SIDEMENU_LIST_TEXT_OFFSET_X 15.0f
#define SIDEMENU_LIST_TEXT_OFFSET_Y 8.0f

// Context Menu
#define CM_WIDTH 120.0f
#define CM_ROW_HEIGHT 25.0f
#define CM_TEXT_OFFSET_X 5.0f
#define CM_TEXT_OFFSET_Y 5.0f
#define CM_TEXT_SIZE 10

// Save Dialog
#define SAVE_DIALOG_WIDTH 300.0f
#define SAVE_DIALOG_HEIGHT 100.0f
#define SAVE_DIALOG_TEXT_Y_OFFSET 40.0f
#define SAVE_DIALOG_TEXT_X_OFFSET 140.0f
#define SAVE_DIALOG_INPUT_Y_OFFSET 10.0f
#define SAVE_DIALOG_INPUT_HEIGHT 30.0f
#define SAVE_DIALOG_INPUT_WIDTH 280.0f
#define SAVE_DIALOG_EXT_OFFSET 285.0f
#define SAVE_FILENAME_MAX_LEN 63

// Help Menu
#define HELP_MENU_WIDTH 320.0f
#define HELP_MENU_HEIGHT 400.0f
#define HELP_PADDING 10.0f
#define HELP_SHADOW_OFFSET 5.0f
#define HELP_HEADER_SIZE 20
#define HELP_TEXT_SIZE 10
#define HELP_LINE_SPACING 15.0f
#define HELP_SECTION_SPACING 25.0f

// HUD
#define HUD_HZ_X_OFFSET 100.0f
#define HUD_HZ_Y 10.0f
#define HUD_FONT_SIZE 20

#endif
