#ifndef SULLA_SIM_CONFIG_H
#define SULLA_SIM_CONFIG_H

#define PIN_SIZE 8.0f
#define PIN_COLLISION_RADIUS_MOD 1.5f
#define PIN_SPACING 20.0f
#define PIN_Y_OFFSET_BASE 10.0f
#define PIN_LABEL_CENTER_GAP 6.0f
#define PIN_LABEL_FONT_SIZE 8
#define PIN_LABEL_INSET 8.0f
#define WIRE_COLLISION_THRESHOLD 10.0f
#define WIRE_HITBOX_PADDING 4.0f
#define WIRE_HITBOX_SIZE 6.0f
#define WIRE_THICKNESS 2.0f
#define WIRE_ARROW_SIZE 6.0f
#define SIM_STEP_BUDGET_SEC 0.008
#define PART_COMPILER "clang++"
#define ZOOM_MIN 0.1f
#define ZOOM_MAX 5.0f
#define ZOOM_SPEED 0.1f
#define INPUT_REPEAT_DELAY 0.5f
#define INPUT_REPEAT_RATE 0.05f

#endif
