#ifndef SULLA_THEME_COLORS_H
#define SULLA_THEME_COLORS_H
#include <raylib/raylib.h>

#define COLOR_BG_LIGHT RAYWHITE
#define COLOR_GRID_LIGHT Fade(LIGHTGRAY, 0.5f)
#define COLOR_PART_BG_LIGHT WHITE
#define COLOR_PART_BORDER_LIGHT BLACK
#define COLOR_TEXT_LIGHT BLACK
#define COLOR_UI_BG_LIGHT RAYWHITE
#define COLOR_UI_BORDER_LIGHT GRAY
#define COLOR_BG_DARK { 30, 30, 30, 255 }
#define COLOR_GRID_DARK { 60, 60, 60, 255 }
#define COLOR_PART_BG_DARK { 50, 50, 50, 255 }
#define COLOR_PART_BORDER_DARK LIGHTGRAY
#define COLOR_TEXT_DARK RAYWHITE
#define COLOR_UI_BG_DARK { 40, 40, 40, 255 }
#define COLOR_UI_BORDER_DARK { 80, 80, 80, 255 }
#define COLOR_WIRE_OFF BLACK
#define COLOR_WIRE_OFF_DARK LIGHTGRAY
#define COLOR_WIRE_ON DARKGREEN
#define COLOR_WIRE_ON_DARK GREEN
#define COLOR_WIRE_SELECTED Color{255, 232, 31, 255}
#define COLOR_PART_SELECTED Color{255, 232, 31, 255}
#define COLOR_LED_ON GREEN
#define COLOR_LED_OFF DARKGREEN
#define COLOR_LED_OUT_ON RED
#define COLOR_LED_OUT_OFF DARKGRAY
#define COLOR_SELECTION_BOX Fade(BLUE, 0.3f)
#define COLOR_SELECTION_BORDER BLUE

#endif
